apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port that the service will expose
      targetPort: 8000  # Port on the container that the service will forward to
  type: ClusterIP  # Can be LoadBalancer, NodePort, etc. depending on your use case
