apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  labels:
    app: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
