apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  labels:
    app: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
      - name: uploader
        image: sachinpanigrahi/uploader:latest
